#!/usr/bin/env python3

import os
import readline
import subprocess
import sys
import shlex

class MasCliRunner:
  def __init__(self, profile):
    self.profile = profile

  def run(self):
    while True:
      line = self.readline()
      if line is None:
        print("exit")
        break
      if line in ["exit", "quit"]:
        break
      elif line == "":
        continue

      cmds = shlex.split(line)
      subprocess.run(["maas", self.profile] + cmds)

  def readline(self):
    try:
      return input("maas> ").lstrip()
    except (EOFError, KeyboardInterrupt):
      None

if __name__ == "__main__":
  profile = os.environ.get("MAAS_PROFILE")
  if profile is None:
    print("Please set MAAS_PROFILE environment variable")
    sys.exit(1)

  MasCliRunner(profile).run()
